name: Deploy to Azure Container App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and deploy to Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: .
          dockerfilePath: ./Dockerfile
          acrName: containerRegistry
          containerAppName: switcher-news-bot-telegram
          resourceGroup: switcher-news-bot-telegram
          containerAppEnvironment: managedEnvironment-switchernewsbot-8a8d
          ingress: external
          targetPort: 8080
          environmentVariables: |
            PORT=8080
          egistryUsername: ${{ secrets.ACR_USERNAME }}
          registryPassword: ${{ secrets.ACR_PASSWORD }}
